name: MacOS Build and Sign

on:
  push:
    branches: master

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup XCode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI workload
        run: dotnet workload install maui
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v3
        with:
          p12-filepath: 'test-certificate.p12'
          p12-password: ${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}
