name: MacOS Build and Sign

on:
  push:
    branches: master

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup XCode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI workload
        run: |
          dotnet workload install maccatalyst
          dotnet workload install maui
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v3
        with:
          p12-filepath: 'test-certificate.p12'
          p12-password: ${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}
      - name: Download Apple Provisioning Profiles
        uses: Apple-Actions/download-provisioning-profiles@v1.0.8
        with:
          bundle-id: ${{ secrets.APPLE_BUNDLE_ID }}
          profile-type: 'MAC_APP_STORE'
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
      - name: Build
        run: dotnet publish maui-playground/maui-playground.csproj -f net8.0-maccatalyst -c Release -p:ArchiveOnBuild=true -p:EnableAssemblyILStripping=false
      - name: Upload app as Github artifact release
        uses: actions/upload-artifact@v4.6.0
        with:
          name: macos-ci-build
          path: maui-playground/bin/Release/net8.0-maccatalyst/**/*.app/
      - name: Upload app to TestFlight
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: 'maui-playground/bin/Release/net8.0-maccatalyst/**/*.app/'
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
