name: MacOS Build and Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Publish
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        run: |
          dotnet workload install maccatalyst
          dotnet workload install maui

      - name: Create and unlock keychain
        run: |
          security create-keychain -p "" build.keychain
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

      - name: Import Code-Signing Certificates
        run: |
          security import test-certificate.p12 -k build.keychain -P "${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security find-identity -v -p codesigning

      - name: Download Apple Provisioning Profiles
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: ${{ secrets.APPLE_BUNDLE_ID }}
          profile-type: 'MAC_APP_STORE'
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}

      - name: Set Signing Identity
        run: |
          SIGNING_IDENTITY=$(security find-identity -v -p codesigning | grep -oE '"[^"]+"' | head -n 1 | tr -d '"')
          echo "SIGNING_IDENTITY=$SIGNING_IDENTITY" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet publish maui-playground/maui-playground.csproj -f net8.0-maccatalyst -c Release -p:ArchiveOnBuild=true -p:EnableAssemblyILStripping=false /p:CodesignKey=$SIGNING_IDENTITY

      - name: Notarize App
        run: |
          xcrun altool --notarize-app --primary-bundle-id "${{ secrets.APPLE_BUNDLE_ID }}" --username "${{ secrets.APPLE_ISSUER_ID }}" --password "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" --file maui-playground/bin/Release/net8.0-maccatalyst/**/*.app

      - name: Staple Notarization
        run: |
          xcrun stapler staple maui-playground/bin/Release/net8.0-maccatalyst/**/*.app

      - name: Upload to App Store Connect
        run: |
          xcrun altool --upload-app --type macos --file maui-playground/bin/Release/net8.0-maccatalyst/**/*.app --username "${{ secrets.APPLE_ISSUER_ID }}" --password "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}"
