name: MacOS Build and Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Publish
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        run: |
          dotnet workload install maccatalyst
          dotnet workload install maui

      - name: Create and unlock keychain
        run: |
          security create-keychain -p "" build.keychain
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

      - name: Import Code-Signing Certificates
        run: |
          security import mac-installer.p12 -k build.keychain -P "${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}" -T /usr/bin/productsign
          security import test-certificate.p12 -k build.keychain -P "${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security find-identity -v -p codesigning
          security find-identity -v | grep -oE '"[^"]+"' | head -n 1 | tr -d '"'

      - name: Download Apple Provisioning Profiles
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: ${{ secrets.APPLE_BUNDLE_ID }}
          profile-type: 'MAC_APP_STORE'
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
      - name: Move provisioning profile
        run: mv "/Users/runner/Library/MobileDevice/Provisioning Profiles/*.mobileprovision" "/Users/runner/Library/MobileDevice/Provisioning Profiles/*.provisionprofile"
      - name: Set Signing Identity
        id: signing-identity
        run: |
          SIGNING_IDENTITY=$(security find-identity -v -p codesigning | grep -oE '"[^"]+"' | head -n 1 | tr -d '"')
          echo "SIGNING_IDENTITY=$SIGNING_IDENTITY" >> $GITHUB_ENV
          PACKAGE_SIGNING_IDENTITY=$(security find-identity -v | grep -oE '"[^"]+"' | head -n 1 | tr -d '"')
          echo "PACKAGE_SIGNING_IDENTITY=$PACKAGE_SIGNING_IDENTITY" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet publish maui-playground/maui-playground.csproj -f net8.0-maccatalyst -c Release -p:MtouchLink=SdkOnly -p:CreatePackage=true -p:EnableCodeSigning=true -p:EnablePackageSigning=true -p:CodesignKey="${{ env.SIGNING_IDENTITY }}" -p:CodesignProvision="MacCatalyst Test App" -p:CodesignEntitlements="Platforms\MacCatalyst\Entitlements.plist" -p:PackageSignKey="${{ env.PACKAGE_SIGNING_IDENTITY }}" 

      - name: Notarize App
        run: |
          xcrun notarytool submit maui-playground/bin/Release/net8.0-maccatalyst/maccatalyst-x64/maui-playground.pkg --apple-id "${{ secrets.APPLE_ISSUER_ID }}" --team-id "${{ secrets.APPLE_TEAM_ID }}" --password "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" --wait

      - name: Staple Notarization
        run: |
          xcrun stapler staple maui-playground/bin/Release/net8.0-maccatalyst/maccatalyst-x64/maui-playground.pkg

      - name: Upload to App Store Connect
        run: |
          xcrun altool --upload-app --type macos --file maui-playground/bin/Release/net8.0-maccatalyst/maccatalyst-x64/maui-playground.pkg --username "${{ secrets.APPLE_ISSUER_ID }}" --password "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}"
